{
 "title": "Appointments Dashboard",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Appointment Needs Follow Up",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n$__unixEpochTo() AS time,\ncount(\"needsFollowUp\") as value,\ncast(\"needsFollowUp\" as varchar(5)) as metric\nFROM\n\"AppointmentV1\"\nGROUP BY \"needsFollowUp\""
    }
   ]
  },
  {
   "title": "Appointment Lab Case Status",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n$__unixEpochTo() AS time,\ncount(\"labCaseStatus\") as value,\ncast(\"labCaseStatus\" as varchar(1000)) as metric\nFROM\n\"AppointmentV1\"\nGROUP BY \"labCaseStatus\""
    }
   ]
  },
  {
   "title": "Appointment Status",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n$__unixEpochTo() AS time,\ncount(\"status\") as value,\ncast(\"status\" as varchar(1000)) as metric\nFROM\n\"AppointmentV1\"\nGROUP BY \"status\""
    }
   ]
  },
  {
   "title": "Appointment Booked Online",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n$__unixEpochTo() AS time,\ncount(\"bookedOnline\") as value,\ncast(\"bookedOnline\" as varchar(1000)) as metric\nFROM\n\"AppointmentV1\"\nGROUP BY \"bookedOnline\""
    }
   ]
  }
 ]
}