version: '3.7'
services:
  dr-h-co-postgres:
    image: postgres:14.1-alpine
    container_name: dr-h-co-postgres
    # restart: always
    networks:
      - dr-h-co-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME} # The PostgreSQL default database (automatically created at first launch)
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - "./data-postgres/:/var/lib/postgresql/data/"
volumes:
  db:
    driver: local

networks:
  dr-h-co-postgres:
    driver: bridge