version: '3.7'

services:
  nats1:
    image: nats
    container_name: nats1
    command: "-D -c /tmp/nats/myConf/nats.conf -m 8222 --cluster_name test-cluster --name 'nats1' -cluster 'nats://0.0.0.0:4245' -routes 'nats://nats1:4245,nats://nats2:4245,nats://nats3:4245' -js -sd '/tmp/nats/nats1'"
    networks:
      - nats
    ports:
      - '4222:4222'
      - '8222:8222'
      - '9222:9222'
    volumes:
      - ./nats.conf:/tmp/nats/myConf/nats.conf

  nats2:
    image: nats
    container_name: nats2
    command: "-D -p 4222 --cluster_name test-cluster --name 'nats2' -cluster 'nats://0.0.0.0:4245' -routes 'nats://nats1:4245,nats://nats2:4245,nats://nats3:4245' -js -sd '/tmp/nats/nats2'"
    networks:
      - nats
    ports:
      - '4223:4222'
  nats3:
    image: nats
    container_name: nats3
    command: "-D -p 4222 --cluster_name test-cluster --name 'nats3' -cluster 'nats://0.0.0.0:4245' -routes 'nats://nats1:4245,nats://nats2:4245,nats://nats3:4245' -js -sd '/tmp/nats/nats3'"
    networks:
      - nats
    ports:
      - '4224:4222'
networks:
  nats:
    driver: bridge