version: "3.7"

services:
  dr-h-co-api-server:
    build:
      context: ../
      dockerfile: ./api/Dockerfile
    container_name: drhco-api-server
    volumes:
      - ../api/:/api
      - ../core/:/core
    depends_on:
      - dr-h-co-postgres
    ports:
      - "1337:1337"
      - "9229:9229"
      - "9231:9231"
    environment:
      ASCEND_CLIENT_ID: "${ASCEND_CLIENT_ID}"
      ASCEND_CLIENT_SECRET: "${ASCEND_CLIENT_SECRET}"
      ASCEND_ORGANIZATION: "${ASCEND_ORGANIZATION}"
      PORT: "${PORT}"
      LOG_LEVEL: $LOG_LEVEL
      ACCOUNT_LOCKOUT_POLICY_DURATION: $ACCOUNT_LOCKOUT_POLICY_DURATION
      ACCOUNT_LOCKOUT_POLICY_THRESHOLD: $ACCOUNT_LOCKOUT_POLICY_THRESHOLD
      ACCOUNT_LOCKOUT_POLICY_UNLOCK_ON_PASSWORD_RESET: $ACCOUNT_LOCKOUT_POLICY_UNLOCK_ON_PASSWORD_RESET
      PASSWORD_POLICY_DO_NOT_ALLOW_USERNAME: $PASSWORD_POLICY_DO_NOT_ALLOW_USERNAME
      PASSWORD_POLICY_MAX_PASSWORD_HISTORY: $PASSWORD_POLICY_MAX_PASSWORD_HISTORY
      PASSWORD_POLICY_MAX_PASSWORD_AGE: $PASSWORD_POLICY_MAX_PASSWORD_AGE
      PASSWORD_POLICY_VALIDATION_ERROR: $PASSWORD_POLICY_VALIDATION_ERROR
      SESSION_LENGTH: $SESSION_LENGTH
      REVOKE_SESSION_ON_PASSWORD_RESET: $REVOKE_SESSION_ON_PASSWORD_RESET
      EXPIRE_INACTIVE_SESSION: $EXPIRE_INACTIVE_SESSION
      DATABASE_URI: "${DATABASE_URI}"
      DATABASE_DEPLOYMENT: "${DATABASE_DEPLOYMENT}"
      DATABASE_HOST: "${DATABASE_HOST}"
      DATABASE_NAME: "${DATABASE_NAME}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      DATABASE_PORT: "${DATABASE_PORT}"
      DATABASE_TYPE: "${DATABASE_TYPE}" # default value : mongo
      ENVIRONMENT: "${ENVIRONMENT}"
      APP_ID: "${APP_ID}"
      MASTER_KEY: "${MASTER_KEY}"
      PARSE_MOUNT: "${PARSE_MOUNT}" # /parse
      COLLECTION_PREFIX: "${COLLECTION_PREFIX}"
      CLIENT_KEY: "${CLIENT_KEY}"
      REST_API_KEY: "${REST_API_KEY}"
      DOTNET_KEY: "${DOTNET_KEY}"
      JAVASCRIPT_KEY: "${JAVASCRIPT_KEY}"
      FILE_KEY: "${FILE_KEY}"
      FACEBOOK_APP_IDS: "${FACEBOOK_APP_IDS}"
      SERVER_URL: "${SERVER_URL}"
      PUBLIC_SERVER_URL: "${PUBLIC_SERVER_URL_PARSE}"
      MAX_UPLOAD_SIZE: "${MAX_UPLOAD_SIZE}" # 20mb
      GCM_ID: "${GCM_ID}"
      GCM_KEY: "${GCM_KEY}"
      PRODUCTION_PFX: "${PRODUCTION_PFX}"
      PRODUCTION_PASSPHRASE: "${PRODUCTION_PASSPHRASE}"
      PRODUCTION_BUNDLE_ID: "${PRODUCTION_BUNDLE_ID}"
      PRODUCTION_CERT: "${PRODUCTION_CERT}" # prodCert.pem
      PRODUCTION_KEY: "${PRODUCTION_KEY}" # prodKey.pem
      DEV_PFX: "${DEV_PFX}"
      DEV_PASSPHRASE: "${DEV_PASSPHRASE}"
      DEV_BUNDLE_ID: "${DEV_BUNDLE_ID}"
      DEV_CERT: "${DEV_CERT}" # devCert.pem
      DEV_KEY: "${DEV_KEY}" # devKey.pem
      VERIFY_USER_EMAILS: "${VERIFY_USER_EMAILS}" # 0
      PREVENT_LOGIN_WITH_UNVERIFIED_EMAIL: "${PREVENT_LOGIN_WITH_UNVERIFIED_EMAIL}" # false
      EMAIL_MODULE: "${EMAIL_MODULE}" # "" or "parse-server-simple-mailgun-adapter"
      EMAIL_MODULE_OPTIONS: "${EMAIL_MODULE_OPTIONS}"
      EMAIL_FROM: "${EMAIL_FROM}"
      EMAIL_SMTP_PORT: "${EMAIL_SMTP_PORT}"
      EMAIL_HOST: "${EMAIL_HOST}"
      EMAIL_DOMAIN: "${EMAIL_DOMAIN}"
      EMAIL_SMTP_PASSWORD: "${EMAIL_SMTP_PASSWORD}"
      EMAIL_API_KEY: "${EMAIL_API_KEY}"
      EMAIL_USER: "${EMAIL_USER}"
      EMAIL_FROM_NAME: "${EMAIL_FROM_NAME}"
      EMAIL_FROM_EMAIL: "${EMAIL_FROM_EMAIL}"
      EMAIL_DISPLAY_NAME: "${EMAIL_DISPLAY_NAME}"
      EMAIL_REPLY_TO: "${EMAIL_REPLY_TO}"
      EMAIL_VERIFICATION_SUBJECT: "${EMAIL_VERIFICATION_SUBJECT}"
      EMAIL_VERIFICATION_BODY: "${EMAIL_VERIFICATION_BODY}"
      EMAIL_PASSWORD_RESET_SUBJECT: "${EMAIL_PASSWORD_RESET_SUBJECT}"
      EMAIL_PASSWORD_RESET_BODY: "${EMAIL_PASSWORD_RESET_BODY}"
      ENABLE_ANON_USERS: "${ENABLE_ANON_USERS}" # 1
      ALLOW_CLIENT_CLASS_CREATION: "${ALLOW_CLIENT_CLASS_CREATION}" # 1
      PARSE_EXPERIMENTAL_CONFIG_ENABLED: "${PARSE_EXPERIMENTAL_CONFIG_ENABLED}" # 0
      TESTING: "${TESTING}" # 0
      APP_NAME: "${APP_NAME}"
      TRUST_PROXY: "${TRUST_PROXY}"
      S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
      S3_SECRET_KEY: "${S3_SECRET_KEY}"
      S3_BUCKET: "${S3_BUCKET}"
      S3_DIRECT: "${S3_DIRECT}"
      GCP_PROJECT_ID: "${GCP_PROJECT_ID}"
      GCP_KEYFILE_PATH: "${GCP_KEYFILE_PATH}"
      GCS_BUCKET: "${GCS_BUCKET}"
      GCS_DIRECT: "${GCS_DIRECT}"
      AZURE_ACCOUNT: "${AZURE_ACCOUNT}"
      AZURE_CONTAINER: "${AZURE_CONTAINER}"
      AZURE_ACCESS_KEY: "${AZURE_ACCESS_KEY}"
      AZURE_DIRECT: "${AZURE_DIRECT}"
      LIVEQUERY_SUPPORT: "${LIVEQUERY_SUPPORT}"
      LIVEQUERY_CLASSES: "${LIVEQUERY_CLASSES}"
      GRAPHQL_SUPPORT: "${GRAPHQL_SUPPORT}"
      GRAPHQL_SCHEMA: "${GRAPHQL_SCHEMA}"
      TWILIO_ACCOUNT_SID: "${TWILIO_ACCOUNT_SID}"
      TWILIO_AUTH_TOKEN: "${TWILIO_AUTH_TOKEN}"
      TWILIO_PHONE_NUMBER: "${TWILIO_PHONE_NUMBER}"
      SQUARE_SANDBOX_APPLICATION_ID: "${SQUARE_SANDBOX_APPLICATION_ID}"
      SQUARE_SANDBOX_TOKEN: "${SQUARE_SANDBOX_TOKEN}"
      SQUARE_SANDBOX_APPLE_MERCHANT_ID: "${SQUARE_SANDBOX_APPLE_MERCHANT_ID}"
      SQUARE_APPLICATION_ID: "${SQUARE_APPLICATION_ID}"
      SQUARE_TOKEN: "${SQUARE_TOKEN}"
      SQUARE_APPLE_MERCHANT_ID: "${SQUARE_APPLE_MERCHANT_ID}"
      SQUARE_ENVIRONMENT: "${SQUARE_ENVIRONMENT}"
      LARAVEL_BACKEND_DATABASE_HOST: "${LARAVEL_BACKEND_DATABASE_HOST}"
      LARAVEL_BACKEND_DATABASE_USER: "${LARAVEL_BACKEND_DATABASE_USER}"
      LARAVEL_BACKEND_DATABASE_PASSWORD: "${LARAVEL_BACKEND_DATABASE_PASSWORD}"
      LARAVEL_BACKEND_DATABASE_NAME: "${LARAVEL_BACKEND_DATABASE_NAME}"
      NATS: "${NATS}"
    networks:
      - dr-h-co-api-server
      - dr-h-co-mongo
      - dr-h-co-postgres
      - nats
    restart: unless-stopped

  dr-h-co-dashboard:
    image: parseplatform/parse-dashboard:4.1.4
    container_name: dr-h-co-dashboard
    networks:
      - dr-h-co-api-server
    depends_on:
      - dr-h-co-api-server
    environment:
      PARSE_DASHBOARD_ALLOW_INSECURE_HTTP: 1
      PARSE_DASHBOARD_SERVER_URL: ${PARSE_DASHBOARD_SERVER_URL}
      PARSE_DASHBOARD_MASTER_KEY: ${MASTER_KEY}
      PARSE_DASHBOARD_APP_ID: ${APP_ID}
      PARSE_DASHBOARD_APP_NAME: ${APP_NAME}
      PARSE_DASHBOARD_USER_ID: ${USER1}
      PARSE_DASHBOARD_USER_PASSWORD: ${USER1_PASSWORD}
      PORT: 4040
    ports:
      - "4040:4040"

networks:
  dr-h-co-api-server:
    driver: bridge
  dr-h-co-mongo:
    driver: bridge
